#!/bin/sh -e

#DEBHELPER#

if [ "$1" = "remove" ]; then
    dpkg-divert --package seamonkey --rename --remove /usr/bin/seamonkey
fi


if [ "$1" = "remove" ]; then
    dpkg-divert --package seamonkey --rename --remove /usr/bin/seamonkey
fi