#!/bin/sh -e
DESTDIR="/opt/seamonkey"
TMPFILE="/tmp/seamonkey.tar.bz2"
LANGCODE=$(echo "$LANG" | awk -F_ '{print $1}')

case $LANGCODE in
    en|es|fy|ga|zh|zh-CN|zh-TW|cs|nl|en-GB|en-US|fi|fr|ka|de|el|hu|it|ja|nb-NO|pl|pt-BR|pt-PT|ru|sk|es-AR|es-ES|sv-SE)
        LANGCODE=$(echo "$LANG" | sed -e 's/_/-/g' | awk -F. '{print $1}')
        ;;
    C.UTF-8|C)
        LANGCODE="en-US"
        ;;
    *)
        echo "Language code $LANGCODE is not supported."
        exit 1
        ;;
esac

echo "Current Language is ⁝$LANG⁝ = ⁝$LANGCODE⁝"

archs=$(uname -m)
case "$archs" in
    i?86) archs="linux-i686" ;;
    x86_64) archs="linux-x86_64" ;;
esac

# Obtain the latest version number from the SeaMonkey releases page
LATEST_VERSION=$(curl -s https://www.seamonkey-project.org/releases/ | grep -oP 'SeaMonkey \K[0-9]+\.[0-9]+\.[0-9]+' | head -1)

wget "https://archive.seamonkey-project.org/releases/${LATEST_VERSION}/${archs}/${LANGCODE}/seamonkey-${LATEST_VERSION}.${LANGCODE}.${archs}.tar.bz2" -O $TMPFILE
cd /tmp
mkdir -p $DESTDIR
tar xjvf $TMPFILE -C $DESTDIR --strip-components=1
rm $TMPFILE
if [ -n "$DISPLAY" ]; then
    echo current installed version:
    $DESTDIR/seamonkey --full-version
fi
