.TH SEAMONKEY "November 4, 2019" Seamonkey "Linux User's Manual"
.SH NAME
seamonkey - open-source web browser and internet suite

.SH SYNOPSIS
.B seamonkey
[\fIOPTIONS\fR] [\fIURL\fR]

.B /opt/seamonkey/seamonkey
[\fIOPTIONS\fR] [\fIURL\fR]

.SH DESCRIPTION
\fBSeamonkey\fR is an open-source web browser and internet suite, designed for standards compliance, performance, and portability. It is under active development and includes a web browser, email client, and other internet tools. 

.SH USAGE
If there is a Seamonkey browser already running, \fBseamonkey\fR will
arrange for it to create a new browser window; otherwise, it will start
a new instance.

.SH OPTIONS
A summary of the options supported by \fBseamonkey\fR is included below.

.SS "X11 options"
.TP
.BI \-\-display= DISPLAY
X display to use
.TP
.B \-\-sync
Make X calls synchronous
.TP
.B \-\-no\-xshm
Don't use X shared memory extension
.TP
.BI \-\-xim\-preedit= STYLE
.TP
.BI \-\-xim\-status= STYLE
.TP
.B \-\-g\-fatal\-warnings
Make all warnings fatal

.SS "Mozilla options"
.TP
.B \-h, \-help
Show summary of options.
.TP
.B \-v, \-version
Print Seamonkey version.
.TP
\fB\-P\fR [\fIprofile\fR]
Start with \fIprofile\fR. When no profile is given, displays the Profile Manager. May require \fB\-no\-remote\fR, see below.
.TP
.B \-migration
Start with migration wizard. May require \fB\-no\-remote\fR, see below.
.TP
.B \-ProfileManager
Start with profile manager. May require \fB\-no\-remote\fR, see below.
.TP
.B \-no\-remote
Don't connect to a running Seamonkey instance. This option can be necessary
in conjunction to several of the options above, that won't have any effect
when a Seamonkey instance is running unless \fB\-no\-remote\fR is used at
the same time.
.TP
\fB\-UILocale\fR \fIlocale\fR
Start with \fIlocale\fR resources as User Interface locale. By default, it is
guessed from environment and available locales for Seamonkey.
.TP
.B \-safe\-mode
Starts Seamonkey in safe mode, i.e. disabling all extensions and
showing a bit more debugging messages.
.TP
.B \-jsconsole
Start with Javascript Console
.TP
\fB\-new-window\fR \fIURL\fR
Open \fIURL\fR in a new window in an already running Seamonkey process.
.TP
\fB\-new-tab\fR \fIURL\fR
Open \fIURL\fR in a new tab in an already running Seamonkey process.
.TP
\fB\-chrome\fR \fIurl\fR
Load the specified chrome.

.SH ENVIRONMENT
\fIMOZILLA_DISABLE_PLUGINS\fR - when set, totally disables loading browser plugins
(the ones that appear at the about:plugins url)

.SH FILES
\fI/usr/bin/seamonkey\fR - symbolic link to \fB/opt/seamonkey/seamonkey\fR.
.br

\fI/opt/seamonkey/seamonkey\fR - Seamonkey executable.

\fI/opt/seamonkey/seamonkey\-bin\fR - Legacy executable.
.br

.SH BUGS
To report a bug, please visit \fIhttp://bugzilla.mozilla.org/\fR and/or report bugs
to the Debian Bug Tracking System, as usual.

.SH AUTHORS
.TP
.B The Mozilla Organization
.I http://www.mozilla.org/about.html
